language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4snapshot

matrix:
  allow_failures:
    - php: 7.4snapshot

sudo: false

install:
  - composer install

script:
  - ./vendor/bin/phpunit

notifications:
  email: false

jobs:
  include:
    - stage: "Static Code Analysis"
      script: ./vendor/bin/phpcs
      name: "Coding Standard"
      php: 7.3
    - script: ./vendor/bin/phan --allow-polyfill-parser
      name: "Phan"
      php: 7.3
