language: php

php:
  - 7.4
  - 8.0

sudo: false

install:
  - composer install

script:
  - ./vendor/bin/phpunit

notifications:
  email: false

jobs:
  include:
    - stage: "Static Code Analysis"
      script: ./vendor/bin/phpcs
      name: "Coding Standard"
      php: 7.2
    - script: ./vendor/bin/phan --allow-polyfill-parser
      name: "Phan"
      php: 7.2
