language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4snapshot
  - master

matrix:
  allow_failures:
      - php: master

sudo: false

install:
  - composer install

script:
  - ./vendor/bin/phpunit

notifications:
  email: false
